name: Executar Scraper BEP Automático

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  recortar-e-publicar:
    runs-on: ubuntu-latest
    steps:
    - name: Descarregar Código do Repositório
      uses: actions/checkout@v4

    - name: Configurar Ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Biblioteca de Rede na Nuvem
      run: pip install requests

    - name: Executar Sincronização de Texto Python
      run: python gerar_data.py

    - name: Gravar Alterações no Repositório GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data.json estado.json
        git commit -m "Sistema: Sincronização via Wayback Machine" || echo "Sem novidades"
        git push origin main
