name: Executar Scraper BEP Automático

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  recortar-e-publicar:
    runs-on: ubuntu-latest
    steps:
    - name: Descarregar Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Forçar IP do Estado Português no Sistema
      # Este comando mapeia o domínio diretamente para o IP correto, ignorando o DNS avariado do GitHub
      run: |
        echo "185.34.133.19 www.bep.gov.pt bep.gov.pt" | sudo tee -a /etc/hosts

    - name: Descarregar XML da BEP
      # Usamos obrigatoriamente o link oficial completo com o www. que mapeámos acima
      run: |
        curl -s -L -k -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://bep.gov.pt" -o feed.xml

    - name: Executar o Scraper Python
      run: python gerar_data.py

    - name: Atualizar Repositório
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add data.json estado.json
        git commit -m "Sistema: Atualização automática de dados da BEP" || echo "Sem novidades"
        git push origin main
